### ISSUE TITLE
개발 환경 설정 수정(.eslintrc.json/prettierrc 및 폴더 구조)

### ISSUE THREAD

**Issue by PJW980921** [EmotionalCore/frontend#7]
# 버그 수정 🔥
### 버그 발생한 코드 및 설명

- { 
 // .prettierrc
. . .
"semi:false;
- //eslintrc.json ( 버그 수정한 코드에 설명을 함께 작성해뒀습니다. )
. . .
    ],
    "tailwindcss/classnames-order": "error,
    "tailwindcss/no-custom-classname": "wran"
  }
}

- src/components 

### 버그 수정한 코드 및 설명
- // .prettierrc
. . .
"semi:true;
가독성을 고려하여 세미콜론 여부를 활성화 했습니다.

-  // eslintrc.json  . . .
    ],
    "tailwindcss/classnames-order": "off, 
/* tailwind css 클래스명을 알파벳 순서로 정렬하도록 요구하는 규칙입니다.
현재 개발환경 설정에서는 plugin 으로 tailwind css 클래스명을 정렬하기 때문에 off로 설정을 해야합니다. *\
    "tailwindcss/no-custom-classname": "off"
/*이 규칙은 JSX 또는 HTML에서 정의 되지 않은 사용자 정의 클래스명을 사용할 때 경고 및 오류를 발생시키는 규칙입니다.
 현재 저희 개발환경 설정은 커스텀클래스를 사용하고있기 때문에 wran이 아닌 off로 설정을 해야합니다.  *\

  }
}

- src/components -> src/app/components 폴더 구조 변경
/*Next.js 공식문서를 참고하였습니다. *\

**Comment by SJ-1220** [comment]
No comment
